### ISSUE TITLE
apply in wxPythonDemos/BlitTest.py

### ISSUE THREAD

**Issue by pydemo** [PythonCHB/wxPythonDemos#2]
File "/Users/abuzunov/mygit/wxPythonDemos/BlitTest.py", line 76, in random_color
    return apply(wx.Colour,(random.randrange(255),random.randrange(255),random.randrange(255)))
NameError: name 'apply' is not defined
OnInit returned false, exiting...

where's apply defined?

**Comment by PythonCHB** [comment]
I believe that's python2 -- no longer available in py3.

can't test now, but that looks like it could be easily replaced with:

`return wx.Colour((random.randrange(255),random.randrange(255),random.randrange(255)))`

really not sure why the apply was ever neccesary.

Sorry -- some really old code in there still!

If you make the change, and it works, and you do a PR, I'll merge it. 

Thanks!

**Comment by PythonCHB** [comment]
Fixed in 155a061697263ab5b6380829e0
